language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t smileajw1004/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true smileajw1004/react-test-app npm run test

after_success:
  - docker build -t sonickaka/docker-frontend ./frontend
  - docker build -t sonickaka/docker-backend ./backend
  - docker build -t sonickaka/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push sonickaka/docker-frontend
  - docker push sonickaka/docker-backend
  - docker push sonickaka/docker-nginx

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker-fullstack-app"
 env: "DockerFullstackApp-env"
 bucket_name: elasticbeanstalk-ap-northeast-2-662683496420
 bucket_path: "docker-fullstack-app"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY
